version: '3.4'

services:

  collector:
    container_name: dockerflow-collector
    restart: always
    image: hudsonventura/dockerflow-collector:0.5.3
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" #necessário para acesso a API do Docker
      - "./appsettings.json:/app/appsettings.json"
    networks:
      - dockerflow-network
    depends_on:
      - db

  api:
    container_name: dockerflow-api
    restart: always
    image: hudsonventura/dockerflow-api:0.5.3
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" #necessário para acesso a API do Docker
      - "./appsettings.json:/app/appsettings.json"
    #ports:
    #  - 5000:5000
    networks:
      - dockerflow-network
    depends_on:
      - db

  db:
    container_name: dockerflow-db
    restart: always
    image: "postgres:14"
    environment:
      POSTGRES_USER: dockerflow
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: America/Cuiaba
    #volumes:
    #  - ./pgdata:/var/lib/postgresql/data/pgdata
    #ports:
    #  - "5432:5432"
    mem_limit: 128m
    networks:
      - dockerflow-network


networks:
  dockerflow-network:
    driver: bridge
